### ISSUE TITLE
Make logrus injectable

### ISSUE THREAD

**Issue by janisz** [allegro/mesos-executor#18] opened 2017-11-29 12:59 UTC
There is a problem when we try to use mesos-executor as a lib. All dependecies shoud be wrapped with an interface and injectable.

```
Solving failure: No versions of github.com/allegro/mesos-executor met constraints:
 	 v0.9.0: Could not introduce github.com/allegro/mesos-executor@v0.9.0, as it depends on github.com/Sirupsen/logrus from https://github.com/sirupsen/logrus.git, but github.com/Sirupsen/logrus is already marked as coming from github.com/Sirupsen/logrus
	 v0.8.2: Could not introduce github.com/allegro/mesos-executor@v0.8.2, as its subpackage github.com/allegro/mesos-executor/metrics is missing. (Package is required by (root).)
	 master: Could not introduce github.com/allegro/mesos-executor@master, as it depends on github.com/Sirupsen/logrus from https://github.com/sirupsen/logrus.git, but github.com/Sirupsen/logrus is already marked as coming from github.com/Sirupsen/logrus
```

**Comment by medzin** [comment] 2017-11-29 14:54
I'm closing this issue because:
* your error is caused by import path change in logrus 1.0 which causes the dep tool to malfunction not by using executor as library
* this project is not a library, it's an application
* we want to have predictable builds - that's why we included vendor folder in the repository and we cannot remove it (Go libraries should not commit vendor to repo)

**Closed by medzin** 2017-11-29 14:54 UTC
